### ISSUE TITLE
Error response.status === 200 in file SignupForm.js

### ISSUE THREAD

**Issue by sonnguyentb21** [rabira-hierpa/project-watchdog#77]
.then((response) => {
        if (response.status === 200) {
          this.setState({ loginSuccess: true });
          window.location.href =
            "http://localhost:3000/signin";
        }
      })
      
      Ps: Fixed

**Comment by rabira-hierpa** [comment]
@sonnguyentb21 Thanks for the fix. 
Closed on #78
